### ISSUE TITLE
TCPProxy support does not work

### ISSUE THREAD

**Issue by youngnick** [projectcontour/ir2proxy#42]
Logged by @slguarderas in projectcontour/contour#2564:

When using the conversion tool, it failed to migrate the tcpproxy portion of the IngressRoute.

Here is the input:
```yaml
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: tls-edge-terminate-prometheus-k8s-thanos
spec:
  virtualhost:
    fqdn: "tls-edge-terminate-prometheus-k8s-thanos{{ domain_apps }}"
    tls:
      secretName: "{{ default_contour_cert }}"
  tcpproxy:
    services:
    - name: prometheus-k8s-thanos
      port: 10901
```

Output:
```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: tls-edge-terminate-prometheus-k8s-thanos
spec:
  virtualhost:
    fqdn: tls-edge-terminate-prometheus-k8s-thanos{{ domain_apps }}
    tls:
      secretName: '{{ default_contour_cert }}'
```

**What did you expect to happen:**
The tcpproxy should have been included in the generated HttpProxy, as in:

```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: tls-edge-terminate-prometheus-k8s-thanos
spec:
  virtualhost:
    fqdn: tls-edge-terminate-prometheus-k8s-thanos{{ domain_apps }}
    tls:
      secretName: '{{ default_contour_cert }}'
  tcpproxy:
    services:
    - name: prometheus-k8s-thanos
      port: 10901
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version:
- Kubernetes version: (use `kubectl version`):  v1.15.3+vmware.1
- Kubernetes installer & version:  VMware
- Cloud provider or hardware configuration:  
- OS (e.g. from `/etc/os-release`):
